# Fill in your logo address (darkmode and lightmode) here
# Dont forget to enable it.
# ------------------------------------------------------------
# 在这里填入你的 Logo 地址 - 包括黑暗/白天模式
# 不要忘记把 enable 改成 true 哦～
logo:
  enable: false
  lightmode: null
  darkmode: null
  rss: null

# Header size
# Select from: ["fullheight", "large", "medium", "default"]
# The page will be scroll to post thumbnail if autoscroll enabled
# ------------------------------------------------------------
# 选择 Header 的大小
# 从大到小依次可以选择：["fullheight", "large", "medium", "default"]
# 如果启用 autoscroll 在进入文章后会自动跳转至文章 Thumbnail 处
header:
  index: large
  other: medium
  autoscroll: true

# Favicon file link
# ------------------------------------------------------------
# Favicon 文件地址
favicon: false

# Datetime format for most of positions
# ------------------------------------------------------------
# 站点内大部分日期的显示格式
timeformat: "MMM, D YYYY"

# Enable Podcast support or not
# 是否启用 Podcast 支持
podcast: true

# Enable Lazyload support or not
# ------------------------------------------------------------
# 是否启用图片懒加载
lazyload: true

# Your Copyright String will be shown in footer
# ------------------------------------------------------------
# 你的版权信息会显示在页脚
copyright: 'All rights reserved.'

# Enable code auto Highlight or not
# Then select one lightmode and darkmode style here:
# https://github.com/highlightjs/highlight.js/tree/main/src/styles
# Please enable 'highlight' in your project _config.yml with 'hljs' field set to true!
# ------------------------------------------------------------
# 是否启用代码渲染
# 之后给代码渲染选择一个夜间/白天模式主题：
# https://github.com/highlightjs/highlight.js/tree/main/src/styles
# 最后，在项目的 _config.yml 中打开 highlight 功能并把 hljs 设置为 true！
highlight:
  enable: true
  lightmode: 'atom-one-light'
  darkmode: 'atom-one-dark'

# Navbar will be shown below your logo with some favicons
# You can select your icons with font-awesome 5
# Config format:
#   ['Link Address', 'Icon Class', 'Text After Icon']
# ------------------------------------------------------------
# Navbar 会展示在页面头部的 Logo 下方
# 你可以去 Font Awesome 5 上面选一些好看的图标
# 配置格式：
#   ['链接地址', '图标类', '图标之后的文字']
navbar:
  - ['mailto:privet@utc3.live', 'fa fa-paper-plane', '']
  - ['https://github.com/guiqiqi/chromate', 'fa fa-github', '']
  - ['/feed.rss', 'fa fa-rss', '']

# Subnav configuration will show below navbar with a horizontal divider
# Configuration format as same as previous
# ------------------------------------------------------------
# Sub Navbar 将会在 Navbar 下方展示并以水平线与之分割
# 配置模式与上面类似
subnav:
  - ['#love', 'fa fa-heart', 'Love']
  - ['#peace', 'fa fa-globe', 'Peace']
  - ['#human', 'fa fa-male', 'Human']

# Menubar and its texts
# ------------------------------------------------------------
# 菜单栏的地址和文字
menubar:
  - ['/about/', 'About']
  - ['/archives/', 'Archives']

# RSS auto generation configuration
#   enable: true or false
#   path: feeding path
#   config:
#     email: your podcast contact email
#     category: {
#       'Apple Podcast Category name': ['Subcategories', ...],
#       ...
#     }
#     explicit: using true if your podcast content is explicit
# ------------------------------------------------------------
# RSS 自动生成器配置
#   enable: 启用为 true
#   path: RSS 订阅地址
#   config:
#     email: 你的 Podcast 联系邮箱
#     category: {
#       'Apple Podcast 分类名': ['子分类列表', ...],
#       ...
#     }
#     explicit: 如果你的播客有羞羞的内容，那么改成 true
rss:
  enable: true
  path: '/feed.rss'
  config:
    email: 'privet@utc3.live'
    category: {
      'Education': ['How To', 'Language Learning'],
      'Technology': []
    }
    explicit: false

# Boardcast info will show in top of the post list
# Color:
#   default: grey
#   danger: red
#   info: blue
#   warning: yellow
# ------------------------------------------------------------
# 站点消息广播 - 会显示在首页的文章列表顶部
# 广播块颜色选择:
#   default: 灰色
#   danger: 红色
#   info: 蓝色
#   warning: 黄色
boardcast: 
  enable: false
  color: default
  message: 'Memorial hero Yuan Longping.'

# Site mourn mode, enable to get a global grayscale filter
# ------------------------------------------------------------
# 站点悼念模式 - 启用后会为站点整体提供灰色滤镜
mourn: false
